### ISSUE TITLE
Angular 0.3.5 breaks validations

### ISSUE THREAD

**Issue by ReinierGielen** [refactorthis/xtform#19]
I have been using your library with much pleasure.

It works fine for me up til Angular 0.3.0.
But last friday I updated to 0.3.5 and I get a lot of red borders in situations when the field is no longer invalid.

So for the moment I reverted to 0.3.0, but I hope you can fix this because xtForm is a really nice extention.

**Comment by refactorthis** [comment]
xtForm has been rewritten for angular 1.3.x and now implements multiple new features. please check the version 2.0.0-beta.1 in bower https://github.com/refactorthis/xtform/tree/development

**Comment by ReinierGielen** [comment]
Thanks for the rewrite and the new features.

As the existing tag no longer function it will take some refactoring.

I tried one screen this morning but I think I do something wrong.
I replaced: xt-validation by xt-validation-tooltip
And I made the form definition like this:
     <form name="userForm" name="userForm" class="form-horizontal" 
role="form" xt-form strategy="focusedAndDirtyOrSubmitted" 
focus-error="true" novalidate>

When I now start the page all fields have a red border. As I have 
novalidate I did not expect that.
Clicking on save sets the focus on the first error and opens the 
tooltip. But the border gets the focus color and not the error color.

And I don't get tooltip's anymore on hover of the error indicated 
fields, only when I click the field.
I would really like the option to choose either.

The content of the tooltip changes(is removed) on filling/improving the 
data in the field, but the red border remains.

After some testing of my page and your demo page I concluded that the 
purpose of the xt-error-container has changed and that xt-error is no 
longer used. In your demo page the red border come from:
.ng-submitted input.ng-invalid,
.ng-submitted select.ng-invalid,
.ng-submitted textarea.ng-invalid {
     border: 1px solid red;
}
in main.css. But this css is not part of the distribution of xtForm so I 
am not getting any error indicating colors.
I think xtForm should have some out of the box CSS that people can 
override with their own code.

I am aware this is a beta version and that this is a mayor rewrite.
So this is all meant as constructive comment.

Please let me know if you need some assistance.

Regards,

Reinier Gielen
