### ISSUE TITLE
$validators

### ISSUE THREAD

**Issue by ReinierGielen** [refactorthis/xtform#27]
As I understand it as from Angular 1.3 form validation is supposed to be done with the new $validators.
This is a special pipeline introduced for handling validations.

As xtForm 2.0 was rewritten for Angular 1.3 I expected this to be used but I do not see it in the source.
I am interested why this structure was not used in xtForm, as it works fine for me in my other directives.

**Comment by refactorthis** [comment]
Hey I don't need to jump in on the $validators or $parsers pipelines as I'm not adding any validation logic. I simply watch the $error object of a ngModel for change and when it changes redraw the errors.
