### ISSUE TITLE
bower install not working

### ISSUE THREAD

**Issue by phpniki** [refactorthis/xtform#29]
Hi dear,

i try yo install via bower : 
bower install --save angular-xtform

but it shown me 
bower                        ENOTFOUND Package angular-xtform not found
what is should to do?

**Comment by JasonPierce** [comment]
@phpniki try `bower install --save xtform`

**Comment by leocaseiro** [comment]
It works, but only for the older version 1.0.1

**Comment by gino8080** [comment]
how to install the latest version with bower?

**Comment by leocaseiro** [comment]
Try `bower install xtform#v2.0.0-beta.2`
