### ISSUE TITLE
Custom validation support?

### ISSUE THREAD

**Issue by freemng** [refactorthis/xtform#41]
I try the xtform and find it very helpful.
But, does the latest version support custom validation?

I found the old example page having example on custom validation,
http://www.brentmckendrick.com/code/xtform/

Many thx.

**Comment by smurugavel** [comment]
I could not see custom validation working so I added my own method to make it work. 
it is easy.. just add your method in xtFormConfig provider and call it in your controller.

**Comment by freemng** [comment]
Thanks for your reply, Vel
However, I have still no much idea on adding my method to xtFormConfig after I review the example and the js file.
Do you mind show me some hints on how can I add the method and use it ?

Many thx.

**Comment by smurugavel** [comment]
Hey freemng,
that was quite a hack.. I added a new method in xtFormConfig provider service which is a replica of xtFormConfig.setErrorMessages, (xtFormConfig's private function) 

this method should be placed inside this.$get. 

Then, I call this method from my controller. function has a single json parameter and json looks similar to _errors. 
Remember to instantiate / inject "xtFormConfig" in your controller to take advantage of your new method.
does this help?

thanks
Vel.

**Comment by idreeshaddad** [comment]
@freemng you can create a custom validator directive, add it to the xtForm module, and broadcast the XtForm.ForceErrorUpdate event.

The directive:

``` javascript
angular.module('xtForm')
    .directive('exactWordValidator', function () {
    return {
        require: 'ngModel',
        link: function (scope, element, attrs, ngModel) {

            var isValid = function (value) {
                return (!value || value === attrs.exactWordValidator);
            };

            ngModel.$parsers.unshift(function (value) {
                var valid = isValid(value);
                ngModel.$setValidity('exactWordValidator', valid);
                scope.$broadcast('XtForm.ForceErrorUpdate', null, 'submit');
                return valid ? value : undefined;
            });
        }
    };
});
```

The view:

``` html
<input id="exactWord" name="exactWord" type="text" placeholder="Must be the word 'hello'" ng-model="exactWord" exact-word-validator="hello" msg-exact-word-validator="word must be 'hello'">
<xt-validation-inline for="exactWord"></xt-validation-inline>
```

@refactorthis Should this be added to the example page?

**Comment by freemng** [comment]
Thanks @idreeshaddad  and @smurugavel
It's work~

**Comment by iviamontes** [comment]
hmm, I think you need to change 
<code>
$scope.$broadcast('XtForm.ForceErrorUpdate', null, 'submit');
</code>
for 
<code>
scope.$broadcast('XtForm.ForceErrorUpdate', null, 'submit');
</code>

I just removed the $.

**Comment by idreeshaddad** [comment]
@iviamontes Yes, you are correct, thank you for noting that.

**Comment by iviamontes** [comment]
Thank to you for your work.
