### ISSUE TITLE
Question: summary of error messages at top of form?

### ISSUE THREAD

**Issue by lderks** [refactorthis/xtform#9]
Is it also possible with xt-form to group the error messages at the top of the form? Something like in the attached screenshot?

![screen shot 2014-05-15 at 12 08 58](https://cloud.githubusercontent.com/assets/1809918/2982736/07f614cc-dc19-11e3-87c7-3012d3b1198e.png)

**Comment by refactorthis** [comment]
Completed in development branch for v2.0
